/**:
  ros__parameters:
    common_ground_filter:
      plugin: "autoware::ground_filter::GroundFilterComponent"
      parameters:
        # Optimized parameters for QCS6490 platform
        global_slope_max_angle_deg: 10.0
        local_slope_max_angle_deg: 13.0 
        split_points_distance_tolerance: 0.2
        use_virtual_ground_point: True
        split_height_distance: 0.2
        non_ground_height_threshold: 0.20
        grid_size_m: 0.15  # Slightly increased for better performance on QCS6490
        grid_mode_switch_radius: 20.0
        ground_grid_buffer_size: 3  # Reduced buffer size for memory optimization
        detection_range_z_max: 2.5
        elevation_grid_mode: true
        low_priority_region_x: -20.0
        center_pcl_shift: 0.0
        radial_divider_angle_deg: 1.5  # Increased for better performance
        use_recheck_ground_cluster: true
        use_lowest_point: true

        # QCS6490 specific parameters
        use_gpu_acceleration: true  # Enable GPU acceleration by default
        use_dsp_acceleration: false
        num_processing_threads: 4  # Optimized for QCS6490 octa-core CPU

        # debug parameters
        publish_processing_time_detail: false